rvm:
  - 2.1
  - 2.2
  - 2.3.0
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - gem update bundler
  - date
  - export TZ=Asia/Tokyo
  - date
